### ISSUE TITLE
Make clean uninstall causes error

### ISSUE THREAD

**Issue by DominicOram** [epics-modules/gtest#1]
I have recently moved the googletest that we use at ISIS over to this one, which is working nicely. However, I have found that running `make clean uninstall` on the googletest directory gives an error of `../../cfg/compat.RULES_BUILD: No such file or directory`  because the clean will remove the `cfg` directory before attempting to clean `onlyGtestSrc` which relies on the compat rules. We'd be happy to fix it but it's not a massive priority for us and I'm not familiar enough with EPICS builds to find an immediate fix. I'll let you know when someone at ISIS who's more familiar puts a fix in.

**Comment by ralphlange** [comment]
I think this is trivial, but let me check first. (Tomorrow.)
Thanks for the feedback and for reporting this!

**Comment by ralphlange** [comment]
Interesting.
This problem appears only when running `make clean uninstall` or `make distclean` **_twice_** in a row. In those cases it is obvious that the rules snippet doesn't exist anymore, since the `uninstall` of the first run removes it, whereas the `clean` of the second run tries to include it.

The fix is trivial.
As the compatibility snippet is only needed for building, but not for cleaning, it is sufficient to use `-include` instead of `include` in the Makefiles that need the compatibility rules. The missing snippet is ignored, and `make clean uninstall` can be called multiple times.

**Comment by DominicOram** [comment]
Works great, thanks! And thank you for the explanation.
